### ISSUE TITLE
nativeBannerAdClicked 🐛  باگ: 

### ISSUE THREAD

**Issue by z85510** [tapsellorg/TapsellPlusSDK-FlutterPlugin#11]
<div dir='rtl'>

**شرح باگ در پلاگین**:
متد nativeBannerAdClicked مقدار true/false برمیگردونه و تبلیغات رو باز نمیکنه 

`InkWell(
            onTap: () {
              TapsellPlus.instance.nativeBannerAdClicked(refId.value);
            },
child: ...
`

</div>

**Comment by mahdi-malv** [comment]
سلام
در لاگ اروری از سمت platform channel چاپ نمیشه؟

**Comment by z85510** [comment]
> سلام در لاگ اروری از سمت platform channel چاپ نمیشه؟

نه هیچ اتفاقی نمیفته ، خروجی متد Future<bool> هست 

D[/TAP_SDK_WaterfallManag]()( 5093): nativeBannerAdClicked() Called.

**Comment by mahdi-malv** [comment]
سلام مجدد
متاسفانه من نتونستم ایشو رو تکرارش کنم و فانکشنالیتی مطابق انتظار کار میکنه
لطفا با اپ سمپل سعی کنید تکرارش کنید یا اینکه راهنمایی کنید که تو چه کیسی میشه reproduce شه
