### ISSUE TITLE
🐛  باگ: 

### ISSUE THREAD

**Issue by mahdiqdi** [tapsellorg/TapsellPlusSDK-FlutterPlugin#16]
<div dir='rtl'>

**شرح باگ در پلاگین**:
سلام یک پروژه جدید فلاتری ایجاد کردم.تپسل رو اضافه کردم.موقع اجرای اپ این ارور رو میده

**متن کامل خطا یا لاگ مرتبط به طور کامل**:
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':tapsell_plus' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  
[✓] Flutter (Channel stable, 3.10.0, on macOS 12.6.1 21G217 darwin-x64, locale en-TR)
    • Flutter version 3.10.0 on channel stable at /Users/mac/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (5 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)
    • SM G950F (mobile) • ce081718dccfdb3901 • android-arm64  • Android 9 (API 28)
    • macOS (desktop)   • macos              • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!

</div>

**Comment by MortezaNedaei** [comment]
please try again with [v2.2.0](https://github.com/tapsellorg/TapsellPlusSDK-FlutterPlugin/releases/tag/v2.2.0)
