### ISSUE TITLE
Update Kotlin Version from 1.5.20 to 1.7.10

### ISSUE THREAD

**Issue by MahdiForughi** [tapsellorg/TapsellPlusSDK-FlutterPlugin#17]
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':tapsell_plus' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10

**Comment by MortezaNedaei** [comment]
[v2.2.0](https://github.com/tapsellorg/TapsellPlusSDK-FlutterPlugin/releases/tag/v2.2.0) is Updated to Kotlin `1.8.20`
