### ISSUE TITLE
مشکل در ios

### ISSUE THREAD

**Issue by sajjad-ser** [tapsellorg/TapsellPlusSDK-FlutterPlugin#2]
با سلام برنامه من در اندروید به خوبی تبلیغات رو نمایش میده ولی در
ios
هیچی نمیاد

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

درود
بروزرسانی 2021

در حال حاضر پلاگین فقط روی اندروید کار میکنه تا سمت نیتیو ios به وضع پایدارتری برسه و بشه استفاده‌ش کرد. لیبل ios از پلاگین برداشته شده.


</div>

**Comment by mahdi-malv** [comment]
Will be re-opened (and resolved) when the native iOS is added to the stack.
