### ISSUE TITLE
عدم نمایش دو بنر استاندارد به صورت همزمان

### ISSUE THREAD

**Issue by niafara** [tapsellorg/TapsellPlusSDK-FlutterPlugin#21]
سلام وقت بخیر
اینجا سوالمو میپرسم چون فکر کردم شاید محدودیت فلاتر هست و مشکلم اینه که من میخوام 2 تا بنر با سایز های مخلتف در یک صفحه برنامه م بزارم که هر کدام از آنها جداگانه کار میکنن و نمایش داده میشن اما همزمان باهمدیگر نمایش داده نمیشن هرچند که توکن نمایش رو دریافت کرده است. حتی با 2 تا بنر استاندارد جدا از هم(2 تا شناسه تبلیغ متفاوت) امتحان کردم نشد و در آن لحظه فقط یک بنر و در یک سایز را نشان میدهد لطفا بفرمایید این محدودیت تپسل هست یا موضوع چیز دیگریست
سپاس

**Comment by MortezaNedaei** [comment]
سلام روز بخیر.
محدودیتی در این مورد در فلاتر وجود نداره. ممکنه پاسخ ad id مربوط به یک request رو دارید همزمان در هر دو بنر نشون میدید که اشتباهه. 
برای هر بنر لازمه request مخصوص به همون بنر زده بشه که یک ad id منحصر به فرد برمیگردونه که لازمه در هر بنر از ad id مخصوص به خودش موقع نمایش استفاده بشه.
