### ISSUE TITLE
🐛  باگ: 

### ISSUE THREAD

**Issue by misteloo** [tapsellorg/TapsellPlusSDK-FlutterPlugin#22]
<div dir='rtl'>

**شرح باگ در پلاگین**:

درود بعد از سینک شده اطالاعات توسط سیستم و در اولین کامپایل پروژه به این خطا بر میخورده بلافاصله در حین بالا اومدن پروژه  

**متن کامل خطا یا لاگ مرتبط به طور کامل**:

FATAL EXCEPTION: main
E/AndroidRuntime(26501): Process: mistelo.soldiercount, PID: 26501
E/AndroidRuntime(26501): java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
E/AndroidRuntime(26501): 
E/AndroidRuntime(26501): ******************************************************************************
E/AndroidRuntime(26501): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(26501): * should follow the instructions here:                                       *
E/AndroidRuntime(26501): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
/AndroidRuntime(26501): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(26501): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(26501): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(26501): ******************************************************************************
2
E/AndroidRuntime(26501): 
E/AndroidRuntime(26501): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7770)
E/AndroidRuntime(26501): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276)
E/AndroidRuntime(26501): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983)
E/AndroidRuntime(26501): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
/AndroidRuntime(26501): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
E/AndroidRuntime(26501): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(26501): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(26501): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(26501): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(26501): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26501): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(26501): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime(26501): Caused by: java.lang.IllegalStateException: 
/AndroidRuntime(26501): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(26501): * should follow the instructions here:                                       *
E/AndroidRuntime(26501): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(26501): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(26501): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(26501): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(26501): ******************************************************************************
E/AndroidRuntime(26501): 	at com.google.android.gms.ads.internal.client.zzek.attachInfo(com.google.android.gms:play-services-ads-lite@@22.0.0:26)
E/AndroidRuntime(26501): 	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@22.0.0:1)
E/AndroidRuntime(26501): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7765)
E/AndroidRuntime(26501): 	... 11 more
Application finished.

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

نسخه grade ۷.۴.۲ و کاتلین ورژن ۱.۸.۲۰

**پکیج نیم برنامه‌**: `mistelo.soldiercount`

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  
همینطور برنامه با گرادل ۸ به طور کامل مشکل داره 
  خطایی که در بالا ذکر شده در پروژه خام فلاتری رخ داده بدون هیچ گونه کتابخانه جانبی
لازم به ذکر هست که طبق کد های پیاده سازی شده در قسمت gradle مربوط به گیتهاب تپسل dependencies اضافه شده است
</div>

**Comment by MortezaNedaei** [comment]
با توجه به [faq](https://docs.tapsell.ir/faq/plus-sdk/flutter/#%D8%AE%D8%B7%D8%A7%DB%8C-eandroidruntime-the-google-mobile-ads-sdk-was-initialized-incorrectly-admob-publishers-should-follow-the-instructions-here-httpsgooglemobileadssdkpagelinkadmob-android-update-manifest-to-add-a-valid-app-id-inside-the-androidmanifest)، کتابخانه تپسل‌پلاس، از کتابخانه `google_mobile_ads` به عنوان وابستگی داخلی استفاده می‌کند. در صورتیکه با این خطا مواجه شدید، لازم است وارد مسیر `android/app/src/main/AndroidManifest.xml` شده و اپ آیدی مورد نیاز اندروید را در آن وارد نمایید. در صورتی که از ادموب استفاده نمیکنید، میتوانید از اپ آیدی تست ادموب (`ca-app-pub-3940256099942544~3347511713`) استفاده کنید. در غیر اینصورت اپ آیدی اختصاصی خود را وارد نمایید.
