### ISSUE TITLE
ارور هنگام بیلد گرفتن

### ISSUE THREAD

**Issue by amir-noroozi** [tapsellorg/TapsellPlusSDK-FlutterPlugin#23]
بعد از اضافه کردن پلاگین تپسل پلاس به پروژه ی خام فلاتر این خطارو دریافت میکنم و اپ فور کلوز میشه:

E/AndroidRuntime(18480): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8488)
E/AndroidRuntime(18480): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7988)
E/AndroidRuntime(18480): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7674)
E/AndroidRuntime(18480): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
E/AndroidRuntime(18480): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
E/AndroidRuntime(18480): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18480): 	at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime(18480): 	at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime(18480): 	at android.app.ActivityThread.main(ActivityThread.java:8918)
E/AndroidRuntime(18480): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18480): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)

E/AndroidRuntime(18480): 	at com.google.android.gms.ads.internal.client.zzek.attachInfo(com.google.android.gms:play-services-ads-lite@@22.0.0:26)
E/AndroidRuntime(18480): 	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@22.0.0:1)
E/AndroidRuntime(18480): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8483)

**Comment by MortezaNedaei** [comment]
از داخل فایل منیفست، این مورد رو چک کنید ببینید انجام شده باشه

https://docs.tapsell.ir/faq/plus-sdk/flutter/#%D8%AE%D8%B7%D8%A7%DB%8C-eandroidruntime-the-google-mobile-ads-sdk-was-initialized-incorrectly-admob-publishers-should-follow-the-instructions-here-httpsgooglemobileadssdkpagelinkadmob-android-update-manifest-to-add-a-valid-app-id-inside-the-androidmanifest
