### ISSUE TITLE
نمایش تبلیغ ویدیو پیش نمایشی

### ISSUE THREAD

**Issue by behjat-amir** [tapsellorg/TapsellPlusSDK-FlutterPlugin#24]
سلام
داخل متود های کتابخونتون متودی نبود برای کال کردن ویدیو پیش نمایشی
چیکار کنم؟

**Comment by MortezaNedaei** [comment]
سلام. تبلیغ PreRoll فقط در پلتفرم نیتیو اندروید ساپورت میشه

**Comment by amir-noroozi** [comment]
ایا به فلاتر اضافش میکنین یا امکانش نیست؟

**Comment by MortezaNedaei** [comment]
تپسل از `Google IMA` برای نمایش تبلیغ پری رول استفاده میکنه. [طبق این کامنت ساپورت گوگل](https://groups.google.com/g/ima-sdk/c/_lVjMTcBIWg/m/6Vpoch1OAQAJ)، هنوز ساپورت IMA برای فلاتر منتشر نشده. ولی در صورتیکه این ساپورت از طرف گوگل اضافه بشه، ما هم امکانش رو اضافه خواهیم کرد
