### ISSUE TITLE
🐛  باگ: 

### ISSUE THREAD

**Issue by AliRezaPython1375** [tapsellorg/TapsellPlusSDK-FlutterPlugin#25]
<div dir='rtl'>

 **شرح باگ در پلاگین**: سلام من طبق سایتتون پیش رفتم ولی موقع اجرا این ارور رو بهم میده. همچنین برنامه کلا باز نمیشهو

**متن کامل خطا یا لاگ مرتبط به طور کامل**:
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Xcode build done.                                           22.2s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Connecting to the VM Service is taking longer than expected...
Still attempting to connect to the VM Service...
If you do NOT see the Flutter application running, it might have crashed. The device logs (e.g. from adb or XCode) might have more details.
If you do see the Flutter application running on the device, try re-running with --host-vmservice-port to use a specific port known to be available.
Exception attempting to connect to the VM Service: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 61521
This was attempt #50. Will retry in 0:00:01.600000.
Exception attempting to connect to the VM Service: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 62559
This was attempt #100. Will retry in 0:00:01.600000.
Exception attempting to connect to the VM Service: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 63589
This was attempt #150. Will retry in 0:00:01.600000.
/div>

**Comment by MortezaNedaei** [comment]
سلام. تپسل از iOS پشتیبانی نمیکنه. با اندروید هم امتحان کردید؟

**Comment by AliRezaPython1375** [comment]
سلامی مجدد من گوشی اندروید رو متصل کردم به سیستم و اجراش کردم ولی بازم نشد
توی مستندات هم نگاه کردم همچین اروری نبود

Restarted application in 2,969ms.
I/flutter (22535): 1
I/flutter (22535): 
E/flutter (22535): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method TapsellPlus.initialize on channel tapsell_plus)
E/flutter (22535): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (22535): <asynchronous suspension>
E/flutter (22535): #1      TapsellPlus.initialize (package:tapsell_plus/tapsell_plus.dart:54:12)
E/flutter (22535): <asynchronous suspension>
E/flutter (22535):

من کد تپسلم رو بعد از ساخت اپلیکیشن برداشتم از سایت

**Comment by AliRezaPython1375** [comment]
سلامی مجدد
ببینید من اپم رو کامل طبق مستندات پیش میبرم
روی گوشی اندروید وقتی اجراش میکنم ارور زیر رو میده و کرش میکنه اپ و بسته میشه:

Launching lib/main.dart on SM A205F in debug mode...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

✓ Built build/app/outputs/flutter-apk/app-debug.apk
E/AndroidRuntime(23222): FATAL EXCEPTION: main
E/AndroidRuntime(23222): Process: com.example.jarvis, PID: 23222
E/AndroidRuntime(23222): java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:
E/AndroidRuntime(23222):
E/AndroidRuntime(23222): ******************************************************************************
E/AndroidRuntime(23222): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(23222): * should follow the instructions here:                                       *
E/AndroidRuntime(23222): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(23222): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(23222): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(23222): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(23222): ******************************************************************************
E/AndroidRuntime(23222): 
E/AndroidRuntime(23222):
E/AndroidRuntime(23222): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6788)
E/AndroidRuntime(23222): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6330)
E/AndroidRuntime(23222): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6245)
E/AndroidRuntime(23222): 	at android.app.ActivityThread.access$1200(ActivityThread.java:237)
E/AndroidRuntime(23222): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1792)
E/AndroidRuntime(23222): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(23222): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(23222): 	at android.app.ActivityThread.main(ActivityThread.java:7091)
E/AndroidRuntime(23222): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23222): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(23222): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/AndroidRuntime(23222): Caused by: java.lang.IllegalStateException:
E/AndroidRuntime(23222):
E/AndroidRuntime(23222): ******************************************************************************
E/AndroidRuntime(23222): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(23222): * should follow the instructions here:                                       *
E/AndroidRuntime(23222): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(23222): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(23222): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(23222): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(23222): ******************************************************************************
E/AndroidRuntime(23222): 
E/AndroidRuntime(23222):
E/AndroidRuntime(23222): 	at com.google.android.gms.ads.internal.client.zzek.attachInfo(com.google.android.gms:play-services-ads-lite@@22.0.0:26)
E/AndroidRuntime(23222): 	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@22.0.0:1)
E/AndroidRuntime(23222): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6783)
E/AndroidRuntime(23222): 	... 10 more


این متن ارور کامل و دقیقش هستش که براتون فرستادم

این هم کدی که ازش استفاده میکنم:


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  await Hive.openBox('userBox');
  await Hive.openBox<List>('chatBox');
  runApp(const MainApp());
  const appId = "";
  TapsellPlus.instance.initialize(appId);


}

ممنون میشم کمکم کنید

**Comment by MortezaNedaei** [comment]
لینک زیر رو انجام بدید

https://docs.tapsell.ir/faq/plus-sdk/flutter/#%D8%AE%D8%B7%D8%A7%DB%8C-eandroidruntime-the-google-mobile-ads-sdk-was-initialized-incorrectly-admob-publishers-should-follow-the-instructions-here-httpsgooglemobileadssdkpagelinkadmob-android-update-manifest-to-add-a-valid-app-id-inside-the-androidmanifest

**Comment by AliRezaPython1375** [comment]
درست شد ممنونم
