### ISSUE TITLE
🐛  باگ: Tapsell SDK is outdated! LOG

### ISSUE THREAD

**Issue by ZhiaDev** [tapsellorg/TapsellPlusSDK-FlutterPlugin#26]
<div dir='rtl'>

**شرح باگ در پلاگین**:
هنگام اجرا کردن اپ متن لاگ زیر در ترمینال چاپ میشود،  آیا باید من کاری انجام دهم که آن را رفع کنم؟

**متن کامل خطا یا لاگ مرتبط به طور کامل**:
`E/TAP_SDK_(32593): Tapsell SDK is outdated! Latest version is 4.8.1. Please update.`

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: `ir.roino.estate`

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  
pubspec.yaml: `tapsell_plus: ^2.2.4`

</div>

**Comment by MortezaNedaei** [comment]
سلام خیر مشکلی نیست.
نیاز نیست کار خاصی انجام بدید
در نسخه های بعد اصلاح میشه

**Comment by ZhiaDev** [comment]
آها پس اوکیه، خیلی ممنونم از اینکه پاسخ دادید
