### ISSUE TITLE
کرش کردن اپ🐛  باگ: 

### ISSUE THREAD

**Issue by SeyyedAmirNimaGhaebi** [tapsellorg/TapsellPlusSDK-FlutterPlugin#28]
<div dir='rtl'>

**شرح باگ در پلاگین**:
زمانی که پکیج رو به پروژه اضافه میکنم اول که خطای DuplicateClasses میده که با ارتقای ورژن کاتلین حل میشه
ولی بعدش میزنم که اپ ران بشه(هنوز از پکیج استفاده نکردم فقط اضافش کردم) بیلد میشه ولی تا میره توی اپ کرش میکنه بدون هیچ اروری
و وقتی کرش میکنه توی vs code هنوز درحال ران گرفتنه و اونجا هم هیچ اروری چاپ نمیشه

**متن کامل خطا یا لاگ مرتبط به طور کامل**:

![Screenshot 2024-07-15 232703](https://github.com/user-attachments/assets/ac77c3c4-87cd-4841-beef-31ea66f77804)

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: `com.example.ad_test`

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by MortezaNedaei** [comment]
سلام [این لینک](https://github.com/tapsellorg/TapsellPlusSDK-FlutterPlugin/issues/22#issuecomment-2060349569) رو بررسی کنید

**Comment by SeyyedAmirNimaGhaebi** [comment]
تشکر حل شد🙏❤️

**Comment by ssssmohammad** [comment]
منم دقیقا این مشکل رو دارم و هنگام ران گرفتن کرش میکنه 
```
            <meta-data
                android:name="com.google.android.gms.ads.APPLICATION_ID"
                android:value="ca-app-pub-3940256099942544~3347511713"/>
``` اینم اضافه کردم مورد حل نشده
چکار کنم؟
