### ISSUE TITLE
🚀[فیچر]:  تبلیغات بنری در ویجت های فلاتر

### ISSUE THREAD

**Issue by AmirNGDev** [tapsellorg/TapsellPlusSDK-FlutterPlugin#29]
<div dir='rtl'>

**شرح نقص یا فیچر درخواستی**  :اضافه کردن تبلیغات بنری در ویجت های فلاتر
برای مثال من یه لیستی دارم میخوام یه تبلیغ بنری توی لیستم داشته باشم که با بقیه آیتم های لیستم یکی باشه 
![Screenshot 2024-07-16 155902](https://github.com/user-attachments/assets/28415ba0-fda9-47ca-8988-ac7e63489239)

</div>

**Comment by MortezaNedaei** [comment]
برای این نوع تبلیغات باید از تبلیغ همسان (Native) استفاده کنید. 
داخل [این لینک](https://github.com/tapsellorg/TapsellPlusSDK-FlutterPlugin/blob/master/example/lib/modal.dart)، یک سمپل که به صورت ویجت فلاتر هست، پیاده سازی شده.

**Comment by moh3n-dev** [comment]
What went wrong:
Execution failed for task ':tapsell_plus:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 21s
Error: Gradle task assembleDebug failed with exit code 1
این مربوط به چیه؟
