### ISSUE TITLE
Security alert in play store

### ISSUE THREAD

**Issue by javadi69** [tapsellorg/TapsellPlusSDK-FlutterPlugin#3]
> Security alert
> 
> Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details.
> 
> Vulnerable classes:
> 
> ir.tapsell.sdk.utils.e.b

**Comment by mahdi-malv** [comment]
Issue should not happen in favor of remaking the plugin. Use `v2.1.3` to get the latest stable changes

Feel free to re-open the issue if the problem was repeated by the current plugin
