### ISSUE TITLE
آقا من پیکیج رو که نصب میکنم کلا پروژه بیلد و دیباگ نمیشه

### ISSUE THREAD

**Issue by moh3n-dev** [tapsellorg/TapsellPlusSDK-FlutterPlugin#30]
**Describe the issue**:

**Paste the error text in your logs**:

**[Optionally paste the whole stacktrace for more details**:

**How to reproduce this issue:**

**App package name**: ``

**Comment by MortezaNedaei** [comment]
با اپ سمپل هم تست کنید. یا جزئیاتی از متن خطا بفرستید تا بررسی بشه
