### ISSUE TITLE
کار نمیکنه

### ISSUE THREAD

**Issue by sky93** [tapsellorg/TapsellPlusSDK-FlutterPlugin#5]
<div dir=rtl>
کلا این sdk که دادین بیرون توی حالت release کار نمیکنه. مجبور شدم minify رو خاموش کنم کار کرد.

هیچ کدوم از تبلیغات بخصوص تبلیغات بنری رو کسی براش کد فلاتر رو پیاده سازی نکرده و صرفا دروغ گفتین که sdk فلاتر دارین. فقط تبلیغات بنری همسان درسته که اونم به درد مفت نمی‌خوره

دولوپر فلاترتون خیلی خیلی بی سواده بهتره هرچه سریع‌تر اخراجش کنید. صرفا یک متد چنل درست کرده دو تا فانکشن رو پورت کرده بقیش هم بلد نبوده بنویسه رها کرده. جمع کنین برین
</div>

**Comment by p4yam** [comment]
میدونم یکم دیره اما گفتم مشکلات sdk رو بهتون بگم تا اگه خواستید خودتون ریپوزیتوری رو فورک کنید و استفاده کنید بدونید چه قسمت هاییش مشکل داره.

1- قسمت اندروید لایبرری کاملا قدیمیه پس اول باید به android x مایگریت بشه.

2- build.gradle های پروژه خیلی قدیمی هستن پس اول android/build.gradle رو بروز کنید و بعد توی app/build.gradle از آخرین نسخه‌ی دیپندنسی تپسل استفاده کنید.

3- کد هایی که نوشته شدن با سیستم قدیمی موتور فلاتر بودن پس باید کد MainActivity.kt و منیفست هم با استفاده از آموزش زیر بروز بشه. (https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)

4- gradle-wraper.properties قدیمیه پس باید به آخرین نسخه به روز بشه.

5- توی فایل TapsellPlusPlugin.kt یه سری جاها نال سیفتی رعایت نشده که خطا میده. من تا جایی که دیدم درستشون کردم(https://github.com/p4yam/TapsellPlusSDK-FlutterPlugin/blob/master/android/src/main/kotlin/ir/tapsell/tapsell_plus/TapsellPlusPlugin.kt#L101)

6- برای من توی رلیز بدون مشکل تبلیغات رو نشون داد اما اگر پروگارد گیر داد میشه پروگاردی که خود تپسل معرفی کرده رو استفاده کرد.

7- من اپ رو هنوز توی گوگل پلی آپدیت نکردم که ببینم بهم گیر میده یا نه. تست می کنم اگر گیر داد همینجا اطلاع میدم.

8- من قسمت ios رو کاری نکردم چون خروجی ios نمی خواستم.

در نهایت اگر می خواید میتونید از کدی که من فورک کردم استفاده کنید اما خب حواستون باشه من فقط قسمت هایی که بدرد خودم می خورده رو ویرایش کردم و بهتره خودتون از اول تست کنید. برای استفاده از کد جدید این رو به pubspec.yaml اضافه کنید:

```
  tapsell_plus:
    git:
      url: git://github.com/p4yam/TapsellPlusSDK-FlutterPlugin.git
      ref: master
```

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

درود
نسخه‌ی ۲.۱.۳ بازنویسی پلاگین رو دربر داره

مشکلات پروگارد حل شده ولی برای اطمینان کلاس‌های پکیج `ir.tapsell.plus.flutter` نگه‌داشته بشه که دو تا کدهای پلاگین رو داره و exclude ruleی نداره. اما کد نیتیو consumer-rules بهش اضافه شده و خودش هنگام minify کردن قوانین لازم رو لحاظ می‌کنه

تمام تبلیغات کار میکنن من جمله استاندارد. اما توی نسخه‌ی بعد قصد داریم PlatformView رو بیاریم که به عنوان ویجت بشه بنر رو آورد توی widget tree

مشکل Null-safety که حل شده و بازنویسی با null-safe dart انجام شده


تغییرات توی [مستندات](https://docs.tapsell.ir/plus-sdk/flutter/main/) ذکر شده و مستندات بروز هست. میتونید چک کنید

</div>

**Comment by mahdi-malv** [comment]
Closing. Feel free to re-open if the issue still exists with the latest released version
