### ISSUE TITLE
https://dl.bintray.com -> Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by aminnzo** [tapsellorg/TapsellPlusSDK-FlutterPlugin#6]
Could not resolve ir.tapsell.plus:tapsell-plus-sdk-android:1.0.10.
Could not get resource 'https://dl.bintray.com/tapsellorg/maven/ir/tapsell/plus/tapsell-plus-sdk-android/1.0.10/tapsell-plus-sdk-android-1.0.10.pom'.
Received status code 403 from server: Forbidden

pub package: tapsell_plus: ^1.0.0

**Comment by mahdi-malv** [comment]
`tapsell_plus`:**2.1.3** uses mavenCentral as the remote. So this issue is fixed then
